-- Migration: Create career_pages table
-- Description: Tracks career page URLs and their scrape status
-- Idempotent: Uses IF NOT EXISTS

BEGIN;

CREATE TABLE IF NOT EXISTS career_pages (
    -- Primary Key: using BIGINT and Identity for Postgres compatibility (replacing AUTOINCREMENT)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Foreign Key to companies table
    company_id BIGINT NOT NULL REFERENCES companies(id),
    
    -- The URL of the career page
    url TEXT NOT NULL,

    -- Tracking fields
    last_hash TEXT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status TEXT DEFAULT 'new',

    -- Constraints
    UNIQUE(company_id, url)
);

COMMENT ON TABLE career_pages IS 'Tracks career page URLs and their scrape status';

COMMIT;
