-- Migration: Create jobs table
-- Description: Stores extracted job listings with status tracking
-- Idempotent: Uses IF NOT EXISTS

BEGIN;

CREATE TABLE IF NOT EXISTS jobs (
    -- BIGINT GENERATED BY DEFAULT AS IDENTITY replaces INTEGER PRIMARY KEY AUTOINCREMENT
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    title TEXT NOT NULL,
    location TEXT,

    department TEXT,

    url TEXT NOT NULL,

    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    status TEXT DEFAULT 'open',

    content_hash TEXT,

    raw_scrape_id BIGINT,   -- link to scrape that found it (great for debugging)

    UNIQUE(company_id, url),

    FOREIGN KEY(company_id) REFERENCES companies(id)
);

COMMENT ON TABLE jobs IS 'Stores extracted job listings from scraped career pages';

COMMIT;
