-- Migration: Create companies table
-- Description: Creates a table to store company names with a unique constraint.
-- Idempotent: Uses IF NOT EXISTS to avoid errors if the table already exists.

-- Start transaction
BEGIN;

-- Create the 'companies' table if it does not already exist
CREATE TABLE IF NOT EXISTS companies (
    -- Unique identifier for the company
    -- Using BIGINT and GENERATED BY DEFAULT AS IDENTITY for Supabase/PostgreSQL compatibility
    -- This matches the standard 'id' field behavior in Supabase
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Name of the company
    -- TEXT type for variable length string
    -- NOT NULL ensures every company has a name
    -- UNIQUE constraint ensures no duplicate company names
    name TEXT NOT NULL UNIQUE
);

-- Add a comment to the table for documentation purposes
COMMENT ON TABLE companies IS 'Stores unique company names for job scraping';

-- Commit transaction
COMMIT;
