-- Migration: Create scrapes table
-- Description: Stores the results of each scraping attempt for a career page.
-- Idempotent: Uses IF NOT EXISTS

BEGIN;

CREATE TABLE IF NOT EXISTS scrapes (
    -- Primary Key: using BIGINT and Identity for Postgres compatibility
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign Key to career_pages
    career_page_id BIGINT NOT NULL REFERENCES career_pages(id),

    -- Content fields
    raw_html TEXT,              -- Raw HTML content (or path to object storage)
    markdown TEXT,              -- Converted markdown content

    -- JSON data
    -- Using JSONB for better performance and flexibility in Postgres
    chunks_json JSONB,          -- JSON array of chunk texts or metadata
    chunk_count INTEGER,

    -- Hash for change detection
    html_hash TEXT,

    -- Status tracking
    status TEXT DEFAULT 'fetched',  
    error_message TEXT,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE scrapes IS 'Stores the results of each scraping attempt for a career page';

COMMIT;
