-- Migration: Job URL content worker lock + ATS throttling system
-- Description: Adds jobs.content_status lock state, job_page_fetches storage,
--              provider_fetch_control caps, and atomic claim/complete functions.
-- Idempotent: Uses IF NOT EXISTS / OR REPLACE patterns

BEGIN;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS content_status TEXT NOT NULL DEFAULT 'open';

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS content_status_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'jobs_content_status_chk'
    ) THEN
        ALTER TABLE jobs
        ADD CONSTRAINT jobs_content_status_chk
        CHECK (content_status IN ('open', 'job_extracting', 'job_extracted'));
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_jobs_content_status_last_seen_at
    ON jobs (content_status, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS job_page_fetches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
    job_url TEXT NOT NULL,
    provider_bucket TEXT NOT NULL,
    host TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    exists_verified BOOLEAN NOT NULL DEFAULT FALSE,
    http_status INTEGER,
    final_url TEXT,
    content_type TEXT,
    raw_html TEXT,
    markdown TEXT,
    html_hash TEXT,
    error_message TEXT,
    worker_run_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    extracted_at TIMESTAMP WITH TIME ZONE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'job_page_fetches_status_chk'
    ) THEN
        ALTER TABLE job_page_fetches
        ADD CONSTRAINT job_page_fetches_status_chk
        CHECK (status IN ('queued', 'extracting', 'extracted', 'failed', 'gone', 'blocked'));
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_job_page_fetches_status_updated_at
    ON job_page_fetches (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_job_page_fetches_provider_status
    ON job_page_fetches (provider_bucket, status);

CREATE TABLE IF NOT EXISTS provider_fetch_control (
    provider_bucket TEXT PRIMARY KEY,
    max_in_flight INTEGER NOT NULL,
    base_delay_ms INTEGER NOT NULL,
    jitter_max_ms INTEGER NOT NULL DEFAULT 0,
    in_flight INTEGER NOT NULL DEFAULT 0,
    next_allowed_at TIMESTAMP WITH TIME ZONE,
    last_outcome TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

INSERT INTO provider_fetch_control (provider_bucket, max_in_flight, base_delay_ms, jitter_max_ms)
VALUES
    ('greenhouse', 3, 1000, 1000),
    ('lever', 3, 1000, 1000),
    ('ashby', 2, 2000, 1000),
    ('workable', 2, 2000, 1000),
    ('smartrecruiters', 2, 2000, 1000),
    ('custom', 1, 3000, 2000),
    ('yc', 1, 5000, 3000)
ON CONFLICT (provider_bucket) DO NOTHING;

CREATE OR REPLACE FUNCTION classify_provider_bucket(url_text TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    normalized TEXT := lower(COALESCE(url_text, ''));
BEGIN
    IF normalized LIKE '%greenhouse%' THEN
        RETURN 'greenhouse';
    ELSIF normalized LIKE '%lever%' THEN
        RETURN 'lever';
    ELSIF normalized LIKE '%ashby%' THEN
        RETURN 'ashby';
    ELSIF normalized LIKE '%workable%' THEN
        RETURN 'workable';
    ELSIF normalized LIKE '%smartrecruiters%' THEN
        RETURN 'smartrecruiters';
    ELSIF normalized LIKE '%ycombinator%' THEN
        RETURN 'yc';
    END IF;

    RETURN 'custom';
END;
$$;

CREATE OR REPLACE FUNCTION claim_next_job_page_fetch(p_worker_run_id TEXT DEFAULT NULL)
RETURNS TABLE (
    fetch_id BIGINT,
    job_id BIGINT,
    job_url TEXT,
    provider_bucket TEXT,
    host TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    candidate RECORD;
    control_row provider_fetch_control%ROWTYPE;
    selected_bucket TEXT;
    locked_job_id BIGINT;
    locked_fetch_id BIGINT;
BEGIN
    FOR candidate IN
        SELECT
            j.id AS candidate_job_id,
            j.url AS candidate_job_url,
            lower(split_part(regexp_replace(j.url, '^https?://', ''), '/', 1)) AS candidate_host
        FROM jobs j
        WHERE j.status = 'open'
          AND j.last_seen_at >= (now() - INTERVAL '2 days')
          AND j.content_status = 'open'
          AND NOT EXISTS (
              SELECT 1
              FROM job_page_fetches jpf
              WHERE jpf.job_id = j.id
                AND jpf.status = 'extracted'
          )
        ORDER BY j.last_seen_at DESC, j.id ASC
        LIMIT 200
    LOOP
        selected_bucket := classify_provider_bucket(candidate.candidate_job_url);

        SELECT *
        INTO control_row
        FROM provider_fetch_control
        WHERE provider_bucket = selected_bucket
        FOR UPDATE;

        IF NOT FOUND THEN
            CONTINUE;
        END IF;

        IF control_row.in_flight >= control_row.max_in_flight THEN
            CONTINUE;
        END IF;

        IF control_row.next_allowed_at IS NOT NULL AND control_row.next_allowed_at > now() THEN
            CONTINUE;
        END IF;

        UPDATE jobs
        SET
            content_status = 'job_extracting',
            content_status_updated_at = now()
        WHERE id = candidate.candidate_job_id
          AND content_status = 'open'
        RETURNING id INTO locked_job_id;

        IF locked_job_id IS NULL THEN
            CONTINUE;
        END IF;

        INSERT INTO job_page_fetches (
            job_id,
            job_url,
            provider_bucket,
            host,
            status,
            worker_run_id,
            updated_at
        )
        VALUES (
            locked_job_id,
            candidate.candidate_job_url,
            selected_bucket,
            candidate.candidate_host,
            'extracting',
            p_worker_run_id,
            now()
        )
        ON CONFLICT (job_id) DO UPDATE
        SET
            job_url = EXCLUDED.job_url,
            provider_bucket = EXCLUDED.provider_bucket,
            host = EXCLUDED.host,
            status = 'extracting',
            worker_run_id = EXCLUDED.worker_run_id,
            error_message = NULL,
            updated_at = now()
        RETURNING id INTO locked_fetch_id;

        UPDATE provider_fetch_control
        SET
            in_flight = in_flight + 1,
            last_outcome = 'claimed',
            updated_at = now()
        WHERE provider_bucket = selected_bucket;

        RETURN QUERY
        SELECT
            locked_fetch_id,
            locked_job_id,
            candidate.candidate_job_url,
            selected_bucket,
            candidate.candidate_host;
        RETURN;
    END LOOP;

    RETURN;
END;
$$;

CREATE OR REPLACE FUNCTION complete_job_page_fetch(
    p_fetch_id BIGINT,
    p_status TEXT,
    p_exists_verified BOOLEAN DEFAULT FALSE,
    p_http_status INTEGER DEFAULT NULL,
    p_final_url TEXT DEFAULT NULL,
    p_content_type TEXT DEFAULT NULL,
    p_raw_html TEXT DEFAULT NULL,
    p_markdown TEXT DEFAULT NULL,
    p_html_hash TEXT DEFAULT NULL,
    p_error_message TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    fetch_row job_page_fetches%ROWTYPE;
    control_row provider_fetch_control%ROWTYPE;
    delay_ms INTEGER;
    next_status TEXT;
BEGIN
    IF p_status NOT IN ('extracted', 'failed', 'gone', 'blocked') THEN
        RAISE EXCEPTION 'Invalid completion status: %', p_status;
    END IF;

    SELECT *
    INTO fetch_row
    FROM job_page_fetches
    WHERE id = p_fetch_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    SELECT *
    INTO control_row
    FROM provider_fetch_control
    WHERE provider_bucket = fetch_row.provider_bucket
    FOR UPDATE;

    UPDATE job_page_fetches
    SET
        status = p_status,
        exists_verified = COALESCE(p_exists_verified, FALSE),
        http_status = p_http_status,
        final_url = p_final_url,
        content_type = p_content_type,
        raw_html = p_raw_html,
        markdown = p_markdown,
        html_hash = p_html_hash,
        error_message = p_error_message,
        updated_at = now(),
        extracted_at = CASE WHEN p_status = 'extracted' THEN now() ELSE extracted_at END
    WHERE id = p_fetch_id;

    IF p_status = 'extracted' THEN
        next_status := 'job_extracted';
    ELSE
        next_status := 'open';
    END IF;

    UPDATE jobs
    SET
        content_status = next_status,
        content_status_updated_at = now()
    WHERE id = fetch_row.job_id;

    IF FOUND AND control_row.provider_bucket IS NOT NULL THEN
        delay_ms := control_row.base_delay_ms + FLOOR(random() * (control_row.jitter_max_ms + 1))::INTEGER;

        UPDATE provider_fetch_control
        SET
            in_flight = GREATEST(in_flight - 1, 0),
            next_allowed_at = now() + ((delay_ms::TEXT || ' milliseconds')::INTERVAL),
            last_outcome = p_status,
            updated_at = now()
        WHERE provider_bucket = fetch_row.provider_bucket;
    END IF;
END;
$$;

COMMIT;
