-- Migration: Create scrape_log_events table, status transition trigger, and Emmet read views
-- Description: Adds immutable scrape event logging + read-only dashboard/event views.
-- Idempotent: Uses IF NOT EXISTS / OR REPLACE patterns

BEGIN;

CREATE TABLE IF NOT EXISTS scrape_log_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    scrape_id BIGINT NOT NULL REFERENCES scrapes(id) ON DELETE CASCADE,
    career_page_id BIGINT NOT NULL REFERENCES career_pages(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    worker TEXT NOT NULL,
    event_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    from_status TEXT,
    to_status TEXT,
    message TEXT,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    worker_run_id UUID,
    CONSTRAINT scrape_log_events_worker_chk CHECK (worker IN ('import_worker', 'site_content_worker', 'core_extraction_worker', 'system')),
    CONSTRAINT scrape_log_events_event_type_chk CHECK (
        event_type IN (
            'status_transition',
            'url_hit',
            'chunk_progress',
            'jobs_extracted',
            'jobs_upserted',
            'scrape_failed',
            'worker_error',
            'heartbeat'
        )
    ),
    CONSTRAINT scrape_log_events_severity_chk CHECK (severity IN ('info', 'warn', 'error'))
);

CREATE INDEX IF NOT EXISTS idx_scrape_log_events_created_at_desc
    ON scrape_log_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scrape_log_events_scrape_created_at_desc
    ON scrape_log_events (scrape_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scrape_log_events_company_created_at_desc
    ON scrape_log_events (company_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scrape_log_events_event_type_created_at_desc
    ON scrape_log_events (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scrape_log_events_to_status_created_at_desc
    ON scrape_log_events (to_status, created_at DESC);

CREATE OR REPLACE FUNCTION log_scrape_status_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO scrape_log_events (
            scrape_id,
            career_page_id,
            company_id,
            worker,
            event_type,
            severity,
            from_status,
            to_status,
            message,
            metrics
        )
        VALUES (
            NEW.id,
            NEW.career_page_id,
            (SELECT cp.company_id FROM career_pages cp WHERE cp.id = NEW.career_page_id LIMIT 1),
            'system',
            'status_transition',
            'info',
            OLD.status,
            NEW.status,
            'Scrape status changed',
            jsonb_build_object('source', 'scrapes.status trigger')
        );
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_log_scrape_status_transition ON scrapes;
CREATE TRIGGER trigger_log_scrape_status_transition
AFTER UPDATE OF status ON scrapes
FOR EACH ROW
EXECUTE FUNCTION log_scrape_status_transition();

CREATE OR REPLACE VIEW scrape_event_feed_v AS
SELECT
    e.id,
    e.created_at,
    e.scrape_id,
    e.career_page_id,
    COALESCE(e.company_id, cp.company_id) AS company_id,
    co.name AS company_name,
    cp.url AS career_page_url,
    e.worker,
    e.event_type,
    e.severity,
    e.from_status,
    e.to_status,
    e.message,
    e.metrics,
    e.worker_run_id
FROM scrape_log_events e
LEFT JOIN career_pages cp ON cp.id = e.career_page_id
LEFT JOIN companies co ON co.id = COALESCE(e.company_id, cp.company_id);

CREATE OR REPLACE VIEW scrape_failures_v AS
WITH ranked_failures AS (
    SELECT
        e.id,
        e.created_at,
        e.scrape_id,
        e.career_page_id,
        COALESCE(e.company_id, cp.company_id) AS company_id,
        co.name AS company_name,
        cp.url AS career_page_url,
        e.worker,
        e.event_type,
        e.severity,
        e.from_status,
        e.to_status,
        COALESCE(e.message, e.metrics->>'error_message', s.error_message) AS error_message,
        e.metrics,
        ROW_NUMBER() OVER (PARTITION BY e.scrape_id ORDER BY e.created_at DESC, e.id DESC) AS rn
    FROM scrape_log_events e
    LEFT JOIN scrapes s ON s.id = e.scrape_id
    LEFT JOIN career_pages cp ON cp.id = e.career_page_id
    LEFT JOIN companies co ON co.id = COALESCE(e.company_id, cp.company_id)
    WHERE e.severity = 'error'
       OR e.event_type IN ('scrape_failed', 'worker_error')
       OR e.to_status IN ('failed', 'core_extraction_failed')
)
SELECT
    id,
    created_at,
    scrape_id,
    career_page_id,
    company_id,
    company_name,
    career_page_url,
    worker,
    event_type,
    severity,
    from_status,
    to_status,
    error_message,
    metrics
FROM ranked_failures
WHERE rn = 1;

CREATE OR REPLACE VIEW scrape_dashboard_live_v AS
WITH status_counts AS (
    SELECT status, COUNT(*)::bigint AS cnt
    FROM scrapes
    GROUP BY status
),
totals AS (
    SELECT COALESCE(SUM(cnt), 0)::bigint AS total_scrapes
    FROM status_counts
),
status_counts_json AS (
    SELECT COALESCE(jsonb_object_agg(status, cnt), '{}'::jsonb) AS status_counts
    FROM status_counts
),
status_percentages_json AS (
    SELECT COALESCE(
        jsonb_object_agg(
            sc.status,
            CASE
                WHEN t.total_scrapes = 0 THEN 0
                ELSE ROUND((sc.cnt::numeric * 100.0) / t.total_scrapes, 2)
            END
        ),
        '{}'::jsonb
    ) AS status_percentages
    FROM status_counts sc
    CROSS JOIN totals t
),
failed_scrapes AS (
    SELECT
        COUNT(*) FILTER (WHERE latest_failed_at >= now() - INTERVAL '24 hours')::bigint AS failed_scrapes_24h,
        COUNT(*)::bigint AS failed_scrapes_all_time
    FROM (
        SELECT scrape_id, MAX(created_at) AS latest_failed_at
        FROM scrape_log_events
        WHERE to_status IN ('failed', 'core_extraction_failed')
           OR event_type = 'scrape_failed'
        GROUP BY scrape_id
    ) f
),
jobs_extracted AS (
    SELECT
        COALESCE(SUM(COALESCE((metrics->>'jobs_cleaned')::bigint, 0)) FILTER (WHERE created_at >= now() - INTERVAL '24 hours'), 0)::bigint AS jobs_extracted_24h,
        COALESCE(SUM(COALESCE((metrics->>'jobs_cleaned')::bigint, 0)), 0)::bigint AS jobs_extracted_all_time
    FROM scrape_log_events
    WHERE event_type = 'jobs_extracted'
),
new_jobs AS (
    SELECT
        COALESCE(SUM(COALESCE((metrics->>'new_jobs')::bigint, 0)) FILTER (WHERE created_at >= now() - INTERVAL '24 hours'), 0)::bigint AS new_jobs_24h,
        COALESCE(SUM(COALESCE((metrics->>'new_jobs')::bigint, 0)), 0)::bigint AS new_jobs_all_time
    FROM scrape_log_events
    WHERE event_type = 'jobs_upserted'
),
websites_hit AS (
    SELECT
        COUNT(DISTINCT metrics->>'url') FILTER (
            WHERE created_at >= now() - INTERVAL '24 hours'
              AND event_type = 'url_hit'
              AND metrics ? 'url'
        )::bigint AS websites_hit_24h,
        COUNT(DISTINCT metrics->>'url') FILTER (
            WHERE event_type = 'url_hit'
              AND metrics ? 'url'
        )::bigint AS websites_hit_all_time
    FROM scrape_log_events
)
SELECT
    t.total_scrapes,
    scj.status_counts,
    spj.status_percentages,
    fs.failed_scrapes_24h,
    fs.failed_scrapes_all_time,
    je.jobs_extracted_24h,
    je.jobs_extracted_all_time,
    nj.new_jobs_24h,
    nj.new_jobs_all_time,
    wh.websites_hit_24h,
    wh.websites_hit_all_time
FROM totals t
CROSS JOIN status_counts_json scj
CROSS JOIN status_percentages_json spj
CROSS JOIN failed_scrapes fs
CROSS JOIN jobs_extracted je
CROSS JOIN new_jobs nj
CROSS JOIN websites_hit wh;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'emmet_readonly') THEN
        CREATE ROLE emmet_readonly NOLOGIN;
    END IF;
END;
$$;

GRANT USAGE ON SCHEMA public TO emmet_readonly;
GRANT SELECT ON scrape_dashboard_live_v TO emmet_readonly;
GRANT SELECT ON scrape_event_feed_v TO emmet_readonly;
GRANT SELECT ON scrape_failures_v TO emmet_readonly;
REVOKE ALL ON TABLE scrape_log_events FROM emmet_readonly;

COMMIT;
